import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {SONGS, arrange, midi, validate, instrumentsOf, Soundtrack} from './dist/music.js';
import {SAMPLE_INDEX} from './dist/assets/samples-index.js';
import './dist/assets/muestras-orquesta.js';
import './dist/assets/muestras-teclas.js';
import './dist/assets/muestras-percusion.js';

// Frozen from the 3.1/3.0 score before any 3.2 music edits, never regenerated by the build.
const ORIGINAL_SCORES = {
  "anden1": [
    "7d892c6e2705e7fdb538b08c003891ffa2479b0c331a2e5cbbeb20daec450da4",
    "825a08d94c22fed370f8dee1346930451fc35cdd1caca33ca693d80134aea1b7"
  ],
  "primera": [
    "d650c1f839168d5cae255727a86f29d0f34c3c63dfc002d808074450e1b973b9",
    "28f40ca04f35884c39b3efab1a1f57926bfca007ad67ecbe3c90cc4d1c805efa"
  ],
  "verano": [
    "06c8cf5e5ff5788f0747cbd4f2f2260ea899bd024eb20b37cfb67350a1640450",
    "1922b88799eb55369bb837f85dbb4d8a465bbf01f4c754d4802eb244071bd3ae"
  ],
  "vialibre": [
    "fe9d796ab486056cd0761f2a73916de82346faa57b2ff3ee4ba7d5cfa8b97a89",
    "c0241a9736571f1fc2656db31e8d5c260d0ca2d428daea4643e3826b5b55ea8a"
  ],
  "tarifa": [
    "58783c8183376feaf6fceb67f8da6e22c01d3c2ae2e6e7b0c091e9c0f997b302",
    "499929251806927a6fc5949a86a2ecd967702e6f02624f055ed0fc29f48b2b7c"
  ],
  "medianoche": [
    "e7670bd7063597672a69f2d2eafbc1485d1df9a851ca99beafdf3ec6e33b83d6",
    "09ac58b037d7e13a4b57d4fb0f6a0b753fa210e8ffe2b3e41f8a15d42b26b5cb"
  ],
  "norte": [
    "dba541d61afff2c70fd74c2fb9ec77ef59cb40cc81f5d05f757edc5ff7a50a5c",
    "da100ce9e5ba8f28f15e45336307521dc5ea5a31bb4a7457036233d3aca6b054"
  ],
  "mediterraneo": [
    "97bff16b3bc2a742c3c993463b85f4a44e1e31cd6ffbe44fe33ef7aaccb6769f",
    "cedf558f2b7132ab6782135fc7b1d04fe1c93e68a29d0d05be57675463d0177d"
  ],
  "ancho": [
    "76e809c0d2d7cd5fbd55394dffe464e8e673d7b84504cdf2a3c41b8889673206",
    "be7c0f998f3a3912780e3d10bceb7c0c546eee22730904e3ff6b91ab92344fe5"
  ],
  "meseta": [
    "3fc2e59cd88b00850001453aa9779471228d42520a6abf74d9947aaa26c2e639",
    "94668e5c5db4c95c43ddafc394d71a1f7fcffa8b1be9026cef38a3bc58eaf816"
  ],
  "pasajeros": [
    "74048a38d4b36420f3e20e0c50809e9e3130726321729f4f87c41a2f4ca95fc1",
    "840bc4d936dd081b394b4ad5fe048c7acaa6d5af8678f81427cad79c83f73e02"
  ],
  "obras": [
    "5e29b1e50185ae08df70dc6fbe8a1fbfab27b7035c42004117c8d38e69e5811a",
    "8224af1d653bd04ba13bc7a7bcd9ce6d37f5b86ae67706926f7247e03b885038"
  ],
  "despenaperros": [
    "1f45ce3a3693fa7339634ba8459b64bb6012cb8685f6543b80188cac98ea8283",
    "faab4af4bea8ecc250dd9f2fbbc36d8dc7fa797f144f6897222d0170150c86b4"
  ],
  "expreso": [
    "5a88175d4cc88fb79608b748522a8920300b35a622e36eacea705846aaf374a6",
    "5fc70e3fc768f5c050f5a0565283703917f5956d0799aa43f1cea345e7d28b60"
  ]
};

const digest = s => createHash('sha256').update(s).digest('hex');
const parse = str => { let beat=0; return str.split(/\s+/).map(token => { const [pitch,length]=token.split(':'); const note={beat,pitch:pitch==='-'?null:midi(pitch),length:+length}; beat+=note.length; return note; }); };
assert.equal(SONGS.length,14);
assert.deepEqual(SONGS.map(s=>s.id),Object.keys(ORIGINAL_SCORES));
let preserved=0;
for (const song of SONGS) {
  for (const [i,part] of ['A','B'].entries()) assert.equal(digest(song[part].mel),ORIGINAL_SCORES[song.id][i],song.id+' '+part+': original melody changed');
  validate(song);
  const arranged=arrange(song), melodic=arranged.events.filter(e=>e.opt.mel), expected=[], spb=60/song.bpm;
  let bar=0;
  for(const part of song.form||['intro','A','B','A2','B2','A','B','A2','outro']) {
    if(part==='intro') {bar+=(song.intro||[0,0,0,0]).length;continue;}
    if(part==='outro') {bar+=(song.outro||[0,0,0,0]).length;continue;}
    const score=song[part[0]==='B'?'B':'A'];
    for(const note of parse(score.mel)) if(note.pitch!==null)expected.push({...note,beat:bar*song.meter+note.beat});
    bar+=score.chords.length;
  }
  assert.equal(melodic.length,expected.length,song.id+': missing or added melody notes');
  for(const [i,note] of expected.entries()) {
    const actual=melodic[i];
    assert.equal(actual.midi,note.pitch,song.id+': melody pitch '+i);
    assert.equal(actual.opt.scoreDur,note.length,song.id+': melody beat duration '+i);
    assert.equal(actual.opt.scoreBeat,note.beat,song.id+': melody beat position '+i);
    assert.ok(Math.abs(actual.dur/spb-note.length*.95)<1e-9,song.id+': audible note duration '+i);
    const fraction=note.beat-Math.floor(note.beat), swung=song.swing&&Math.abs(fraction-.5)<1e-6?Math.floor(note.beat)+.67:note.beat;
    assert.ok(Math.abs(actual.t-swung*spb)<.003,song.id+': changed melody timing '+i);
  }
  preserved+=expected.length;
  assert.ok(arranged.length>0&&Number.isFinite(arranged.length));
  for(const event of arranged.events) {
    assert.ok(Number.isFinite(event.t)&&event.t>=0);
    assert.ok(Number.isFinite(event.dur)&&event.dur>0);
    assert.ok(Number.isFinite(event.midi));
    assert.ok(Number.isFinite(event.vel)&&event.vel>0&&event.vel<=1);
    if(event.opt.g!==undefined)assert.ok(Number.isFinite(event.opt.g)&&event.opt.g>0);
  }
  // Every played instrument has bundled recordings: the new score requires no generic-synth replacement.
  for(const name of instrumentsOf(arranged.events)) {
    assert.ok(SAMPLE_INDEX[name],song.id+': unrecorded instrument '+name);
    const sample=globalThis.IBERIA_SAMPLES[name];
    assert.ok(sample,song.id+': missing bundled sample '+name);
    const layers=sample.kind==='tonal'?sample.layers:[sample.data];
    assert.ok(layers.length>0);
    if(sample.kind==='tonal') {assert.ok(sample.notes.length>0);for(const layer of layers)assert.equal(layer.length,sample.notes.length);}
    for(const layer of layers)for(const encoded of layer) {
      const bytes=Buffer.from(encoded,'base64');assert.ok(bytes.length>512,name+': empty recording');
      assert.ok(bytes.subarray(0,3).toString()==='ID3'||bytes[0]===255,name+': invalid MP3 header');
    }
  }
}
let mood='estacion';const player=new Soundtrack(()=>mood);
for(const [context,opening] of [['estacion','anden1'],['day','primera'],['dusk','meseta'],['night','medianoche']]) {mood=context;assert.equal(player.pick().id,opening);}
for(const context of ['estacion','day','dusk','night']) {
  const selector=new Soundtrack(()=>context), visited=new Set();
  const eligible=SONGS.filter(s=>context==='estacion'?s.family==='estacion':context==='day'?s.mood==='day':s.mood===context);
  for(let i=0;i<eligible.length;i++) {
    const chosen=selector.pick();
    assert.ok(eligible.includes(chosen),context+': selected a song from the wrong context');
    assert.ok(!visited.has(chosen.id),context+': repeated a track before the context playlist was exhausted');
    visited.add(chosen.id);selector.current={song:chosen};
  }
  selector.mode='repeat';assert.equal(selector.pick(),selector.current.song,context+': repeat mode changed the song');
}
player.mode='list';player.current={song:SONGS.at(-1)};assert.equal(player.pick(),SONGS[0],'List mode should wrap to the first track');
console.log('Banda sonora: 14 partituras originales, '+preserved+' notas conservadas, muestras integradas y contextos verificados.');
